### ISSUE TITLE
log4js doesn't work with PM2 cluster mode

### ISSUE THREAD

**Issue by mogongzi** [nomiddlename/log4js-node#265]
Hi all,

I used log4js clustered appender in my app and which is launched by PM2 under cluster mode. However, the log file cannot be generated successfully. If I run this with node command and use cluster in the code module in the code file, the log was generated as expected. Could you please give me any suggestion?

TIA

Ryan

**Comment by markus138** [comment]
I got the same problem. Did you figure out a solution?

**Comment by songguangyu** [comment]
I got the same problem. Did you figure out a solution?

**Comment by nomiddlename** [comment]
Cluster support has changed in log4js 2.x. Please re-open if this is still a problem.

**Comment by cula** [comment]
@nomiddlename  Unfortunately, the problem still exists on log4js 2.1.0. The following is my log4js config and pm2 config:

import _ from 'lodash';
import config from './config';
import log4js from 'log4js';
import path from 'path';
import fse from 'fs-extra';

const defaultLayout = {
    type: 'pattern',
    pattern: '%d %p %c %z - %m'
};

const colouredLayout = {
    type: 'coloured',
    pattern: '%d %p %c %z - %m'
    // pattern: '%d %[%p%] %c %z %[-%] %m'
};

const appenders = {};
if (config.getOrElse('logging.console.enabled', true)) {
    appenders['console'] = {
        type: 'stdout',
        layout: colouredLayout
    };
}

if (config.getOrElse('logging.file.enabled', false)) {
    const logFile = path.resolve(config.getOrElse('logging.file.filename', '/tmp/viz/main.log'));
    fse.ensureDirSync(path.dirname(logFile));
    appenders['file'] = {
        type: 'dateFile',
        filename: logFile,
        pattern: '.yyyy-MM-dd',
        compress: true,
        backups: config.getOrElse('logging.file.backups', 14),
        layout: defaultLayout,
        alwaysIncludePattern: false
    };

};

if (config.getOrElse('logging.es.enabled', false)) {
    appenders['logstash'] = {
        type: 'logstashUDP',
        host: config.getOrElse('logging.es.hostname'),
        port: config.getOrElse('logging.es.port', 9200),
        fields: {
            service: 'iot2-console'
        },
        layout: defaultLayout

    };
}

log4js.configure({
    appenders: appenders,
    categories: {
        default: {
            appenders: _.keys(appenders),
            level: config.getOrElse('logging.level', 'debug')
        }
    }
});

export default log4js.getLogger('default');

pm2.json:
{
  "apps": [
    {
      "name": "bce-console-viz",
      "script": "./bin/www",
      "instances": 0,
      "max_memory_restart" : "256M",
      "exec_mode": "cluster",
      "source_map_support": true
    }
  ]
}

Changing instances in pm2.json from 0 to 1 does not solve the problem

**Comment by nomiddlename** [comment]
Yep, the problem is pm2 running everything as workers - writing out logs only happens on the master process in log4js. At the very least you're going to need some way of detecting that you're running in PM2 and turning off the cluster support - at least then you would get some log output. The only problem you've got then is that you can't have all the workers using the same configuration - multiple processes writing to the same file will cause problems (the log stash logging would work then though). I'll look into PM2 a bit more, and see if there's anything else I can do.

**Comment by nomiddlename** [comment]
This may be the way to fix it: http://pm2.keymetrics.io/docs/usage/environment/#specific-environment-variables

**Comment by cula** [comment]
So it means I have to deal with multi-instance cases myself with multiple-processes appender in pm2 cluster mode?

**Comment by nomiddlename** [comment]
You're right, the multi-process appender won't work in your case without having three different ports. I'll work on a proper fix - I think with that environment variable in the link above I should be able to detect when log4js is running in PM2 and use it to write out logs on only one worker process.

**Comment by cula** [comment]
I've downgraded to v1.1.1 and looking forward to v2.1.1. Hope it will come asap. Thank u very much.

**Comment by nomiddlename** [comment]
I've got this working - I just need to fix up some tests. It will need the [pm2-intercom](https://github.com/Unitech/pm2/issues/1826) module installed to work, hope that isn't a problem for your setup.

**Comment by jhfoo** [comment]
+1 also looking forward to the fix!

**Comment by nomiddlename** [comment]
Published to nom in version 2.3.0 - details on how to get it working are on the [FAQ](https://nomiddlename.github.io/log4js-node/faq.html) page.

**Comment by cula** [comment]
@nomiddlename 
I tried log4js 2.3.0 with pm2 2.6.1 and pm2-intercom 1.0.0 on node 8.2.1. But this still did not work. My configs are as follows:
pm2.json:
`{
  "apps": [
    {
      "name": "iot-viz",
      "script": "./bin/www",
      "instances": 0,
      "instance_var": "INSTANCE_ID",
      "exec_mode": "cluster"
    }
  ]
}`

logger.config:
`
const _ = require('lodash');
const config = require('./config');
const log4js = require('log4js');
const path = require('path');
const fse = require('fs-extra');

const pattern = '%d %p %c %z - %m';

const appenders = {};
if (config.getOrElse('logging.console.enabled', true)) {
    appenders['console'] = {
        type: 'stdout',
        layout: {type: 'coloured', pattern}
    };
}

if (config.getOrElse('logging.file.enabled', false)) {
    const logFile = path.resolve(config.getOrElse('logging.file.filename', '/tmp/viz/main.log'));
    fse.ensureDirSync(path.dirname(logFile));
    appenders['file'] = {
        type: 'dateFile',
        filename: logFile,
        pattern: '.yyyy-MM-dd',
        compress: true,
        backups: config.getOrElse('logging.file.backups', 14),
        layout: {type: 'pattern', pattern},
        alwaysIncludePattern: false
    };
};

if (config.getOrElse('logging.es.enabled', false)) {
    appenders['logstash'] = {
        type: 'logstashUDP',
        host: config.getOrElse('logging.es.hostname'),
        port: config.getOrElse('logging.es.port', 9200),
        fields: {
            service: 'iot2-console'
        },
        layout: {type: 'pattern', pattern}
    };
}

log4js.configure({
    pm2: true,
    pm2InstanceVar: 'INSTANCE_ID',
    appenders: appenders,
    categories: {
        default: {
            appenders: _.keys(appenders),
            level: config.getOrElse('logging.level', 'debug')
        }
    }
});

module.exports = log4js.getLogger('default');`

**Comment by nomiddlename** [comment]
Looks like you've done the right things - I didn't test with node-config. I'll see what I can work out. If you want to do some investigating yourself, you can pass the "DEBUG=log4js:*" environment variable to your pm2 workers - maybe there will be a clue there.

**Comment by nomiddlename** [comment]
I've just tested with pm2 2.6.1, node v8.2.1, pm2-intercom 1.0.0 and it worked fine. I haven't tried including node-config yet.

Here is a link to my test code: https://gist.github.com/nomiddlename/99b7530281debc926d5e7b8a3b87350f

Your setup looks a lot more complicated than that - is there any chance you could try something simpler, just for us to be able to work out where the problem is?

**Comment by cula** [comment]
It works!
The reason of the last case was that I mistook 'pm2 install' by 'npm install'. 
Now I've deployed my code on production. 
Thank u very much~

**Comment by nomiddlename** [comment]
That's great news, glad to hear it.

**Comment by nomiddlename** [comment]
I noticed a bug in v2.3.0 - logs don't get written for the process with instance id = 0. It's fixed in v2.3.2. Sorry about that.

**Comment by cula** [comment]
I came with a another bug with pm2. May be there is something wrong in your last fix in pm2.

The following is my case:

![1](https://user-images.githubusercontent.com/5352723/29202660-f0ccb4de-7e9c-11e7-9fd0-965fd3612e76.png)

In the pic, 'test' and 'testtest' are two individual services which both use log4js and run in pm2 cluster mode. But the logs are not the expect. The reason mybe the following.

`function workerDispatch(logEvent) {
  debug(`sending message to master from worker ${process.pid}`);
  process.send({ topic: 'log4js:message', data: serialise(logEvent) });
}`

`  if (isPM2Master()) {
    debug('listening for PM2 broadcast messages');
    process.removeListener('message', receiver);
    process.on('message', receiver);
  } else if (cluster.isMaster) {
    cluster.removeListener('message', receiver);
    cluster.on('message', receiver);
  }`

When using pm2-intercom, this function will send message to all workers, 'test' and 'testtest' in my case. It seems like the 'test' service may log the info from the 'testtest' service as well. I also found 'testtest' does not its own info after the info were logged by 'test'. But not sure. 

However, the log4js does not work right in the case in the pic. I'm digging out why. What I'm sure is that the worker sent message in the workerDispatch but master does not receive it. Seems like consumed by another master?

**Comment by AmShaegar13** [comment]
Wow. It took me forever to recognize I have to use `pm2 install pm2-intercom` instead of `npm install pm2-intercom`. Thanks @cula for pointing this out!

**Comment by randomsock** [comment]
I still don't think we're quite there ...

I am seeing logging from my PM2 cluster but **only from the first process**, instance 0.  I can see traffic being handled by the other processes, but no logging from them.

### Versions

Node v6.10.3
PM2 v2.4.6
pm2-intercom v1.0.0
log4js v2.3.3

### Configuration

	log4js.configure({
		pm2: true,
		appenders: {
			out: { type: "stdout" }
		},
		categories: {
			default: {
				appenders: [ "out" ],
				level: "debug"
			}
		}
	});

### PM2 Startup

	{
		"apps": [
			{
				"name": "foo",
				"script": "src/server.js",
				"exec_mode": "cluster",
				"instances": 0
			}
		]
	}

### Output

	[PM2][WARN] Applications foo not running, starting...
	[PM2] App [foo] launched (4 instances)
	+---------------------------------------------------------------------------------------------+
	¦ App name    ¦ id ¦ mode    ¦ pid   ¦ status ¦ restart ¦ uptime ¦ cpu ¦ mem       ¦ watching ¦
	+-------------+----+---------+-------+--------+---------+--------+-----+-----------+----------¦
	¦ foo         ¦ 38 ¦ cluster ¦ 1237  ¦ online ¦ 0       ¦ 0s     ¦ 98% ¦ 25.0 MB   ¦ disabled ¦
	¦ foo         ¦ 39 ¦ cluster ¦ 1243  ¦ online ¦ 0       ¦ 0s     ¦ 92% ¦ 21.9 MB   ¦ disabled ¦
	¦ foo         ¦ 40 ¦ cluster ¦ 1253  ¦ online ¦ 0       ¦ 0s     ¦ 83% ¦ 16.8 MB   ¦ disabled ¦
	¦ foo         ¦ 41 ¦ cluster ¦ 1267  ¦ online ¦ 0       ¦ 0s     ¦ 74% ¦ 15.5 MB   ¦ disabled ¦
	+---------------------------------------------------------------------------------------------+
	 Module activated
	+----------------------------------------------------------------------------+
	¦ Module       ¦ version ¦ target PID ¦ status ¦ restart ¦ cpu ¦ memory      ¦
	+--------------+---------+------------+--------+---------+-----+-------------¦
	¦ pm2-intercom ¦ 1.0.0   ¦ N/A        ¦ online ¦ 0       ¦ 0%  ¦ 29.777 MB   ¦
	+----------------------------------------------------------------------------+
	 Use `pm2 show <id|name>` to get more details about an app
	$ pm2 logs foo
	[TAILING] Tailing last 15 lines for [foo] process (change the value with --lines option)
	/home/pm2/.pm2/logs/foo-error-38.log last 15 lines:
	/home/pm2/.pm2/logs/foo-out-39.log last 15 lines:
	/home/pm2/.pm2/logs/foo-error-39.log last 15 lines:
	/home/pm2/.pm2/logs/foo-out-41.log last 15 lines:
	/home/pm2/.pm2/logs/foo-error-41.log last 15 lines:
	/home/pm2/.pm2/logs/foo-out-40.log last 15 lines:
	/home/pm2/.pm2/logs/foo-error-40.log last 15 lines:
	/home/pm2/.pm2/logs/foo-out-38.log last 15 lines:
	38|foo     | [2017-09-07 12:47:33.448] [INFO] server - foo v0.4.0 loading
	38|foo     | [2017-09-07 12:47:34.306] [INFO] server - Listening on :::3130

	[STREAMING] Now streaming realtime logs for [foo] process
	38|foo     | [2017-09-07 12:48:14.051] [INFO] server - 172.26.52.13 GET /api/stuff 200 6525 47 ms

Hard to demonstrate this but I can hit the service with requests and see them being balanced across all processes, but it's only ever the first process - id 38 in this case - that logs anything.  In the tails above, the same startup messages should appear from each process, for example.

**Comment by nomiddlename** [comment]
This has definitely worked for me, so I know it's possible :)

Try running with the `DEBUG=log4js:*` environment variable - you should get some debug info in the individual log files that might give us a clue (warning: there will be a lot of output).

**Comment by randomsock** [comment]
Sure, and I have to say I've seen it working too while I've been trying to narrow it down, just not consistently.  Also, when it does work, all the logging _appears_ to come from the first process as far as PM2 reports it, although I can put the instance ID in the message to prove the source is actually the right worker - confusing.

Anyway, here's an example of only logging the first process at all, with debugging.

For reference:

	+---------------------------------------------------------------------------------------------+
	¦ App name    ¦ id ¦ mode    ¦ pid   ¦ status ¦ restart ¦ uptime ¦ cpu ¦ mem       ¦ watching ¦
	+-------------+----+---------+-------+--------+---------+--------+-----+-----------+----------¦
	¦ imagen      ¦ 78 ¦ cluster ¦ 2103  ¦ online ¦ 0       ¦ 4m     ¦ 0%  ¦ 45.9 MB   ¦ disabled ¦
	¦ imagen      ¦ 79 ¦ cluster ¦ 2109  ¦ online ¦ 0       ¦ 4m     ¦ 0%  ¦ 46.2 MB   ¦ disabled ¦
	¦ imagen      ¦ 80 ¦ cluster ¦ 2119  ¦ online ¦ 0       ¦ 4m     ¦ 0%  ¦ 45.4 MB   ¦ disabled ¦
	¦ imagen      ¦ 81 ¦ cluster ¦ 2133  ¦ online ¦ 0       ¦ 4m     ¦ 0%  ¦ 45.2 MB   ¦ disabled ¦
	+---------------------------------------------------------------------------------------------+
	 Module activated
	+----------------------------------------------------------------------------+
	¦ Module       ¦ version ¦ target PID ¦ status ¦ restart ¦ cpu ¦ memory      ¦
	+--------------+---------+------------+--------+---------+-----+-------------¦
	¦ pm2-intercom ¦ 1.0.0   ¦ N/A        ¦ online ¦ 0       ¦ 0%  ¦ 34.031 MB   ¦
	+----------------------------------------------------------------------------+

...

	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:logger sending log data (WARN) to appenders
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main Received log event  LoggingEvent {
	78|imagen  |   startTime: 2017-09-07T15:28:44.692Z,
	78|imagen  |   categoryName: 'server',
	78|imagen  |   data: [ '10.144.157.253 GET /api/ping 304 undefined 25 ms' ],
	78|imagen  |   level: Level { level: 30000, levelStr: 'WARN', colour: 'yellow' },
	78|imagen  |   context: {},
	78|imagen  |   pid: 2103,
	78|imagen  |   cluster: { workerId: 3176, worker: 2103 } }
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:28:44 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | [2017-09-07 17:28:44.692] [WARN] server - 10.144.157.253 GET /api/ping 304 undefined 25 ms
	
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for server
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: returning config for default category
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for default
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: default exists in config, returning it
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for server
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: returning config for default category
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for default
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: default exists in config, returning it
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for server
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: returning config for default category
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for default
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: default exists in config, returning it
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for server
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: returning config for default category
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: searching for config for default
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main configForCategory: default exists in config, returning it
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:logger sending log data (INFO) to appenders
	79|imagen  | Thu, 07 Sep 2017 15:28:51 GMT log4js:main sending message to master from worker 2109
	
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for server
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: returning config for default category
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for default
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: default exists in config, returning it
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for server
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: returning config for default category
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for default
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: default exists in config, returning it
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for server
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: returning config for default category
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for default
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: default exists in config, returning it
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for server
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: returning config for default category
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: searching for config for default
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main configForCategory: default exists in config, returning it
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:logger sending log data (INFO) to appenders
	80|imagen  | Thu, 07 Sep 2017 15:29:22 GMT log4js:main sending message to master from worker 2119
	
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for server
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: returning config for default category
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for default
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: default exists in config, returning it
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for server
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: returning config for default category
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for default
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: default exists in config, returning it
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for server
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: returning config for default category
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for default
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: default exists in config, returning it
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for server
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: returning config for default category
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: searching for config for default
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main configForCategory: default exists in config, returning it
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:logger sending log data (INFO) to appenders
	81|imagen  | Thu, 07 Sep 2017 15:29:32 GMT log4js:main sending message to master from worker 2133
	
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:logger sending log data (INFO) to appenders
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main Received log event  LoggingEvent {
	78|imagen  |   startTime: 2017-09-07T15:29:38.831Z,
	78|imagen  |   categoryName: 'server',
	78|imagen  |   data: [ '10.144.157.253 GET /api/ping 200 17 11 ms' ],
	78|imagen  |   level: Level { level: 20000, levelStr: 'INFO', colour: 'green' },
	78|imagen  |   context: {},
	78|imagen  |   pid: 2103,
	78|imagen  |   cluster: { workerId: 3176, worker: 2103 } }
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for server
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: returning config for default category
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: searching for config for default
	78|imagen  | Thu, 07 Sep 2017 15:29:38 GMT log4js:main configForCategory: default exists in config, returning it
	78|imagen  | [2017-09-07 17:29:38.831] [INFO] server - 10.144.157.253 GET /api/ping 200 17 11 ms

**Comment by NextZeus** [comment]
```

log4js.configure({
	pm2: true,
	appenders: {
		...
	},
	categories: {
		...
	}
});

```
worked for me !

log4js@^2.3.3  
pm2@2.5.0

**Comment by randomsock** [comment]
Thanks @NextZeus - can you confirm:
1. this is in a cluster, with more than 1 instance, and
2. you are seeing output from all instances in that cluster, and the PM2 id at the beginning of the line reflects that too

?

**Comment by randomsock** [comment]
@nomiddlename, not a swipe at all, a genuine question from people here who are very grateful to have benefitted from your efforts for a long time: Why does 2.x suddenly introduce issues with PM2, and a new dependency on pm2-intercom?  0.x has served us flawlessly in PM2 clusters for so long, and still does in Node v6.11.3 and PM2 v2.6.1.  I'm struggling to answer why people should consider upgrading or what the future might be.  TIA.

**Comment by NextZeus** [comment]
@randomsock 

this is my pm2 process below:

![image](https://user-images.githubusercontent.com/10203487/30538337-09575060-9ca0-11e7-8a15-319980527a39.png)

pm2 ecosystem.json config:

![image](https://user-images.githubusercontent.com/10203487/30538375-59119232-9ca0-11e7-8ceb-dd179ff0489b.png)

log4js config:

![image](https://user-images.githubusercontent.com/10203487/30538440-95c7a28e-9ca0-11e7-9922-d5a66ff1c655.png)

**Comment by nomiddlename** [comment]
@randomsock changes were made to the cluster support so that log4js will behave nicely in a standard nodejs cluster, so that you don't get multiple processes writing to the same file or trying to rotate the same file. If you're not using file appenders, then this won't have been an issue for you. This approach broke the pm2 support (it would only log on a master process, but there are no master processes in pm2, only children). So I introduced pm2-intercom to broadcast messages to all children and choose one of them to do all the logging. Again, this will fix problems of multiple pm2 processes writing to the same file. But if you weren't using file appenders anyway, it may get confusing. The correct behaviour in version 2.3.x upwards (with pm2-intercom) would be for all of your log4js messages to be output on a single pm2 process. Is this what you're seeing? Or are you missing some log output entirely?

**Comment by cula** [comment]
@randomsock I'm also sure that log4js works fine in the above case after `pm2 install pm2-intercom` because nomiddlename commit a proper fix for this specific case and I test it as well. Thx @nomiddlename 

> Also, when it does work, all the logging appears to come from the first process as far as PM2 reports it

This is what expected. 

But it seems the problem is that `pm2-intercom` broadcasts all messages to all instances. So if there are more than 2 pm-master instance, the logs will going to the both two master.  This will happen if you deploy more than one service in cluster mode on the same pm2 daemon process. That's what I came cross.

What's more, the logs going to wrong master are missing instead of repeated, that is what i un expected. 
So, I guess the reason of the above may also be the reason of your missing logs sometimes though your case seems there is only one service.

Hope this will help u

**Comment by cula** [comment]
> So I introduced pm2-intercom to broadcast messages to all children and choose one of them to do all the logging. 

@nomiddlename I think there maybe some problems if there is two or more than pm2-master instance. As far as I concerned, I found all of these receive the broadcast messages which caused my problem. And your message topic does not identify different services.

**Comment by nomiddlename** [comment]
@cula yep - you're right. Not sure if that is the problem for @randomsock though.

**Comment by cula** [comment]
May I know is there plan to fix this? @nomiddlename 
I found no milestone.

**Comment by randomsock** [comment]
Thanks both for all the info, it's starting to make sense what/why now.

@nomiddlename 

> But if you weren't using file appenders anyway, it may get confusing.

Yep, exactly that.  We've always let log4js do the formatting and output, and let PM2 et al do the log file control externally, so only ever used the console appender.  OK, so I understand what the aim and challenge was now.  But even so, we can't see any longer which process any given output has come from, without going back into the code and explicitly including that in the message (and learning to ignore the PM2 instance id at the front).  For now though, we are missing some output entirely still, but I think that might be explained by ...

@cula 

> the logs going to wrong master are missing instead of repeated, that is what i un expected ...  though your case seems there is only one service

I think that _does_ explain it then.  My apologies, I have misled you with the output earlier - I cut out lines about other services from the `pm2 ls` table for brevity, but in fact we **do** have multiple clusters per PM2 daemon because we deploy multiple microservices into a dedicated service account.  (Note to self: show the whole truth in future, it might be relevant!).

**Comment by nomiddlename** [comment]
I've created #547 for the problems with multiple applications per pm2 daemon. I'm also working on a configuration option to turn off the cluster support, which should revert the behaviour to the way it used to work.

**Comment by randomsock** [comment]
Awesome, thanks a lot

**Comment by nickminutello** [comment]
Is pm2-intercom still supported npm package? pm2 install seems to want to do a git-clone to install (which is so very blocked from my location)

**Comment by nomiddlename** [comment]
pm2-intercom has always seemed a bit dodgy - for some people it never works at all anyway. It didn't need to use git clone when I installed it. Best plan might be to use the `disableClustering` option in your log4js config, log to stdout and let pm2 handle the files as it normally would.

**Comment by Davetwo** [comment]
pm2-intecom is not needed. Just add
```
pm2: true,
disableClustering: true
```
into log4js config.
